project:
  type: website

website:
  title: "12th Iberian Prion Congress"
  reader-mode: true
  page-footer: "&copy; 2023-2024 Website developed by Micha≈Ç Burdukiewicz, Carlos Pintado-Grima (IBB-UAB) and Sara Canoyra Sanchez (CSIC)"
  navbar:
    background: primary
    search: true
    pinned: true
    left:
      - text: "Home"
        file: index.qmd
      - registration.qmd
      - abstract.qmd
      - venue.qmd
      - accommodation.qmd
      - text: "Speakers"
        file: keynotes.qmd
      - text: "About Santiago"
        file: visitsantiago.qmd
    
format:
  html:
    page-layout: full
    theme: united
    css: styles.css
    toc: true
    toc-location: left
    toc-title: " "
